version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  pre_build:
    commands:
      - aws s3 cp s3://config.grimpunt.be/environment.prod.ts src/environments/environment.$ENV.ts
      - aws s3 cp s3://config.grimpunt.be/.beta-env .env
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run deploy
cache:
  paths:
    - node_modules
