version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build:beta
  post_build:
    commands:
      - npm run deploy
cache:
  paths:
    - node_modules
